### ISSUE TITLE
(question)does this library use a memory pool?

### ISSUE THREAD

**Issue by dman82499** [btwael/SuperString#8]
Just wanted to ask whether this library (both C++ and python) uses a memory pool. I skimmed through the code but couldn't find it, so I just thought I'd ask if there is one in play. I am a student and I'm mainly just curious to understand how the optimizations were made

**Comment by btwael** [comment]
Hello,

No, this library does not use any kind of memory pools. The concept is known as Rope Datastructure. So by example when concatenating two strings (S1 and S2) into a string S3, instead of creating a new string with a size equals two the sum of the size of S1 and S2 (size(S3) = size(S1) + size(S2)), we will only make an object that refers to both S1 and S2 (size(S3) = 2*size(of a pointer)), and hence all other operations are defined to use the pointer to S1 and S2 (so when you want the length of S3, we will return the length of S1 + length of S2. If you want to iterate over S3, the iterator iterate over S1 then S2). You can check the python version it's easy to understand and illustrate the concept better.
